### PR TITLE
deploy docs using gh-pages

### PR DESCRIPTION
**Pull request by 2bndy5**
Introduces a new workflow that:
- only runs on master branch
- deploys docs on any commit to master (since this repo does not use releases)
- uses the commit's SHA hash (1<sup>st</sup> 7 alphanumeric characters -- as displayed in commit history) to append the Doxyfile's "PROJECT_NUMBER" tag with a "patch" number. This tag change is not committed to the Doxyfile, rather it is only used during the workflow. Any bump in version will now need to be done from the workflow file.

Additionally, I've
- made fixes for all "addressable" doxygen warnings (`Makefile` is parsed like a C source file because there is no extension -- its a doxygen problem)
    - This includes removing deprecated tags from the Doxyfile (they were using default or invalid options anyway). I didn't use `doxygen -u` for backward compatibility reasons.
- formatted and updated the doxygen-custom.css file
- renamed all links to docs from tmrh20.github.io/\<repo name> to nRF24.github.io/\<repo name> except for:
    - the links to the automatic install/update script at [tmrh20's RF24Installer for RPi](https://github.com/TMRh20/tmrh20.github.io/tree/master/RF24Installer/RPi)
    - any links that lead to tmrh20.github.io main page listing all RF24 repos (links for this page have to be changed separately in the [tmrh20.github.io repo's index.html file](https://github.com/TMRh20/tmrh20.github.io/blob/587d08b7b1cc9185fb6bb1185fbf3f42e1546acd/index.html#L33)
- deactivated any LATEX or XML output from doxygen since they're not actually being used (and the LATEX output seems to require 3rd party software to generate properly).

### CODE REVIEW

**Comment by 2bndy5** [comment]
@TMRh20  How are the docs for this repo currently being published? I ask because I see a green checkmark next the previous commit, and there aren't any actions setup on this specific repo.

image

Is this just the result of the repo's current "source" option in the Github pages settings?

**Comment by TMRh20** [comment]
I dunno, its still being done manually.

**Comment by TMRh20** [comment]
I made a commit by editing the readme.md, but the docs don't appear to have been deployed. Any ideas or am I missing something?

**Comment by 2bndy5** [comment]
what are the settings for this repo concerning the "GitHub Pages" section? Can I have temporary access (like expires in a week)?

**Comment by TMRh20** [comment]
> Can I have temporary access

Done. I changed the setting too.

**Comment by 2bndy5** [comment]
Seems like I don't need that access anymore 😆 . After you changed the settings the docs are now properly published. 😄

**Pull request merged**
